
name: Docker Image CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
         name: Checkout
         uses: actions/checkout@master
      - 
         name: Change Screenshots Links
         run: sed 's#截图](images/#截图](https://github.com/std4453/mikanarr/raw/master/images/#g' ./README.md
      - 
         name: Sync Readme
         uses: meeDamian/sync-readme@v1.0.6
         with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKER_PASS }}
          slug: ${{ secrets.DOCKERHUB_USERNAME }}/mikanarr
          readme: ./README.md
          description: Mikanarr, a bridge between Mikan Anime and Sonarr
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: triatk/mikanarr:latest
