
name: Docker Image CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: triatk/mikanarr:latest
      - uses: actions/checkout@master
      - run: ls -l -a
      - uses: meeDamian/sync-readme@v1.0.6
          with:
            user: ${{ secrets.DOCKERHUB_USERNAME }}
            pass: ${{ secrets.DOCKERHUB_TOKEN }}
            slug: ${{ secrets.DOCKERHUB_USERNAME }}/mikanarr
            readme: ./README.md
            description: A RSS feed convert tool for Sonarr.
